// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow that analyzes spending habits and suggests safer spending windows.
 *
 * - suggestSpendingWindows - A function that analyzes spending habits and suggests safer spending windows.
 * - SuggestSpendingWindowsInput - The input type for the suggestSpendingWindows function.
 * - SuggestSpendingWindowsOutput - The return type for the suggestSpendingWindows function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestSpendingWindowsInputSchema = z.object({
  spendingHistory: z.string().describe('A detailed history of the user\'s spending habits, including dates, amounts, and categories.'),
  currentBalance: z.number().describe('The user\'s current account balance.'),
  income: z.number().describe('The user\'s monthly income.'),
  bills: z.string().describe('A list of bills that the user has to pay and the due dates.'),
});
export type SuggestSpendingWindowsInput = z.infer<typeof SuggestSpendingWindowsInputSchema>;

const SuggestSpendingWindowsOutputSchema = z.object({
  suggestedSpendingWindows: z.string().describe('A list of suggested spending windows, including dates and amounts, based on the user\'s financial situation.'),
  explanation: z.string().describe('An explanation of why the spending windows were suggested.'),
});
export type SuggestSpendingWindowsOutput = z.infer<typeof SuggestSpendingWindowsOutputSchema>;

export async function suggestSpendingWindows(input: SuggestSpendingWindowsInput): Promise<SuggestSpendingWindowsOutput> {
  return suggestSpendingWindowsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestSpendingWindowsPrompt',
  input: {schema: SuggestSpendingWindowsInputSchema},
  output: {schema: SuggestSpendingWindowsOutputSchema},
  prompt: `You are a personal finance advisor. Analyze the user's spending habits and suggest safer spending windows.

  Here is the user's spending history: {{{spendingHistory}}}
  Here is the user's current balance: {{{currentBalance}}}
  Here is the user's monthly income: {{{income}}}
  Here is a list of the user\'s bills: {{{bills}}}

  Based on this information, suggest some safer spending windows for the user. Include the dates and amounts. Explain why you are suggesting these spending windows.
  `,
});

const suggestSpendingWindowsFlow = ai.defineFlow(
  {
    name: 'suggestSpendingWindowsFlow',
    inputSchema: SuggestSpendingWindowsInputSchema,
    outputSchema: SuggestSpendingWindowsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
